--- 
title: '`r paste(params$yr, "transect training report:", params$grpnoyr)`'
format: 
  dashboard:
    embed-resources: true
    logo: images/tarponlogo.png
    nav-buttons: [github]
    css: styles.css
  
params:
  yr: yr
  grp: grp
  grpnoyr: grpnoyr
  transect: transect
  truvar: truvar
  grpscr: grpscr
  allgrpscr: allgrpscr
  scrsum: scrsum
  
execute:
  echo: false
  warning: false
  message: false
---

```{r}
source(here::here('R/funcs.R'))
load(file = here::here('data/trndat.rda'))

yr <- params$yr
grp <- params$grp
grpnoyr <- params$grpnoyr
transect <- params$transect
truvar <- tibble::as_tibble(params$truvar) # do not use as.data.frame, names get coerced
grpscr <- tibble::as_tibble(params$grpscr) 
allgrpscr <- tibble::as_tibble(params$allgrpscr)
scrsum <- params$scrsum

evalgrp <- evalgrp_fun(trndat, yr, grp, truvar)

cards <- purrr::map(
  c('Abundance', 'Blade Length', 'Short Shoot Density'), 
  ~ card_fun(evalgrp, grp, allgrpscr, .x)
  )
```

# Scores

## Row {height=50%}

### Column {.tabset}

```{r}
#| title: "Overall summary"
gt::html(scrsum)
```
  
```{r}
#| title: "Transect summary"
evaltrntab_fun(evalgrp)
```

## Row {height=50%}

```{r}
bslib::layout_column_wrap(width = '250px', fill = F, cards[[1]], cards[[2]], cards[[3]])
```

# How to improve

## Row {height=50%}

```{r}
#| title: "Abundance"
scrimp_fun(allgrpscr, grp, 'Abundance')
```

```{r}
#| title: "Blade Length"
scrimp_fun(allgrpscr, grp, 'Blade Length')
```

```{r}
#| title: "Short Shoot Density"
scrimp_fun(allgrpscr, grp, 'Short Shoot Density')
```

## Row {height=50%}

```{r}
#| title: "Seagrass identification"
sppimp_fun(evalgrp, 'seagrass')
```

```{r}
#| title: "Macroalgae identification"
sppimp_fun(evalgrp, 'macroalgae') 
```

::: {.card title="Additional resources"}
* [Seagrass Transect Training: Protocols](https://youtu.be/jfnVlIjJ-o4?si=xSyZtFT_8h96j7gu){target="_blank"}
* [Seagrass Transect Training: Web Portal](https://youtu.be/cF9VluXSq0E?si=f4nz5_Ju4_yPnJI0){target="_blank"}
* [Species Identification Guide](https://drive.google.com/file/d/1naZpND_Ur90abqND-ZhZ_fJtBBiuetjt/view){target="_blank"}
* [Web Portal](https://dev.seagrass.wateratlas.usf.edu/){target="_blank"}
* [Water Atlas Seagrass Page](https://tampabay.wateratlas.usf.edu/seagrass-monitoring/){target="_blank"}
* [Seagrass Transect Dashboard](https://shiny.tbep.org/seagrasstransect-dash){target="_blank"}
:::